# Generated by Django 4.1.4 on 2023-01-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='created',
            new_name='pub_date',
        ),
    ]
